// PeoplePay360 - OpenAPI 3.0 Aligned Mock Fixtures for Standalone & Fallback Operation

export const mockUsers = [
  {
    id: 'u-admin',
    email: 'admin@peoplepay360.com',
    emp_id: 'EMP001',
    role: 'ADMIN',
    is_active: true,
  },
  {
    id: 'u-hr',
    email: 'maya@peoplepay360.com',
    emp_id: 'EMP002',
    role: 'HR_MANAGER',
    is_active: true,
  },
  {
    id: 'u-payroll',
    email: 'nisha@peoplepay360.com',
    emp_id: 'EMP003',
    role: 'HR_PAYROLL_MANAGER',
    is_active: true,
  },
  {
    id: 'u-emp',
    email: 'rohan@peoplepay360.com',
    emp_id: 'EMP004',
    role: 'EMPLOYEE',
    is_active: true,
  },
];

export const mockEmployees = [
  {
    id: 'emp-1',
    employee_code: 'PP-1042',
    first_name: 'Ananya',
    last_name: 'Sharma',
    name: 'Ananya Sharma',
    email: 'a.sharma@peoplepay360.internal',
    initials: 'AS',
    dept: 'Engineering',
    department_name: 'Engineering',
    position: 'Lead Staff Architect',
    job_title: 'Lead Staff Architect',
    lead: 'Elena Vance',
    location: 'Bengaluru Hub',
    status: 'ACTIVE',
    avatar: 'https://i.pravatar.cc/150?u=1',
  },
  {
    id: 'emp-2',
    employee_code: 'PP-1089',
    first_name: 'Marcus',
    last_name: 'Brody',
    name: 'Marcus Brody',
    email: 'm.brody@peoplepay360.internal',
    initials: 'MB',
    dept: 'Product & UX',
    department_name: 'Product & UX',
    position: 'Senior UX Designer',
    job_title: 'Senior UX Designer',
    lead: 'Ananya Sharma',
    location: 'London Office',
    status: 'ACTIVE',
    avatar: null,
    bg: 'var(--surface-purple-tint)',
    color: 'var(--primary)',
  },
  {
    id: 'emp-3',
    employee_code: 'PP-0914',
    first_name: 'Elena',
    last_name: 'Vance',
    name: 'Elena Vance',
    email: 'e.vance@peoplepay360.internal',
    initials: 'EV',
    dept: 'People Ops',
    department_name: 'People Ops',
    position: 'Chief People Officer',
    job_title: 'Chief People Officer',
    lead: 'Board of Directors',
    location: 'Mumbai HQ',
    status: 'ACTIVE',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
  },
  {
    id: 'emp-4',
    employee_code: 'PP-1104',
    first_name: 'Vikram',
    last_name: 'Sen',
    name: 'Vikram Sen',
    email: 'v.sen@peoplepay360.internal',
    initials: 'VS',
    dept: 'Sales & Growth',
    department_name: 'Sales & Growth',
    position: 'VP Global Enterprise',
    job_title: 'VP Global Enterprise',
    lead: 'Elena Vance',
    location: 'Singapore',
    status: 'ACTIVE',
    avatar: null,
    bg: 'var(--surface-teal-tint)',
    color: 'var(--secondary)',
  },
  {
    id: 'emp-5',
    employee_code: 'PP-1188',
    first_name: 'Priya',
    last_name: 'Patel',
    name: 'Priya Patel',
    email: 'p.patel@peoplepay360.internal',
    initials: 'PP',
    dept: 'Engineering',
    department_name: 'Engineering',
    position: 'Senior DevOps Engineer',
    job_title: 'Senior DevOps Engineer',
    lead: 'Ananya Sharma',
    location: 'Bengaluru Hub',
    status: 'ACTIVE',
    avatar: 'https://i.pravatar.cc/150?u=3',
  },
  {
    id: 'emp-6',
    employee_code: 'PP-1021',
    first_name: 'David',
    last_name: 'Miller',
    name: 'David Miller',
    email: 'd.miller@peoplepay360.internal',
    initials: 'DM',
    dept: 'Operations',
    department_name: 'Operations',
    position: 'Head of Infrastructure',
    job_title: 'Head of Infrastructure',
    lead: 'Elena Vance',
    location: 'Mumbai HQ',
    status: 'ACTIVE',
    avatar: null,
    bg: '#F1F4F4',
    color: 'var(--text-secondary)',
  },
  {
    id: 'emp-7',
    employee_code: 'PP-1205',
    first_name: 'Aisha',
    last_name: 'Al-Mansoor',
    name: 'Aisha Al-Mansoor',
    email: 'a.mansoor@peoplepay360.internal',
    initials: 'AA',
    dept: 'People Ops',
    department_name: 'People Ops',
    position: 'Payroll Specialist',
    job_title: 'Payroll Specialist',
    lead: 'Elena Vance',
    location: 'Dubai Hub',
    status: 'ACTIVE',
    avatar: null,
    bg: 'var(--surface-purple-tint)',
    color: 'var(--primary)',
  },
];

export const mockDepartments = [
  { id: 'dept-1', name: 'Engineering', code: 'ENG', manager_name: 'Ananya Sharma', headcount: 84, active_contracts: 82 },
  { id: 'dept-2', name: 'Product & UX', code: 'PROD', manager_name: 'Marcus Brody', headcount: 32, active_contracts: 31 },
  { id: 'dept-3', name: 'People Ops', code: 'HR', manager_name: 'Elena Vance', headcount: 18, active_contracts: 18 },
  { id: 'dept-4', name: 'Sales & Growth', code: 'SALES', manager_name: 'Vikram Sen', headcount: 65, active_contracts: 64 },
  { id: 'dept-5', name: 'Finance & Legal', code: 'FIN', manager_name: 'Devika Chawla', headcount: 22, active_contracts: 22 },
  { id: 'dept-6', name: 'Operations', code: 'OPS', manager_name: 'David Miller', headcount: 27, active_contracts: 27 },
];

export const mockContracts = [
  {
    id: 'CNT-2024-0891',
    contract_ref: 'CNT-2024-0891',
    employee: 'Arvind Swaminathan',
    employee_name: 'Arvind Swaminathan',
    empId: 'EMP-1049',
    employee_id: 'emp-1',
    role: 'Product Engineering',
    avatar: 'https://i.pravatar.cc/150?u=a',
    start_date: '01 Aug 2023',
    end_date: '31 Jul 2026',
    wage: '₹2,85,000',
    wage_amount: 285000,
    structure: 'Executive Grade 7',
    status: 'RUNNING',
    expiring: false,
  },
  {
    id: 'CNT-2023-0412',
    contract_ref: 'CNT-2023-0412',
    employee: 'Meera Nambiar',
    employee_name: 'Meera Nambiar',
    empId: 'EMP-0833',
    employee_id: 'emp-2',
    role: 'Corporate Finance',
    avatar: 'https://i.pravatar.cc/150?u=b',
    start_date: '15 Sep 2022',
    end_date: '14 Sep 2024',
    wage: '₹2,10,000',
    wage_amount: 210000,
    structure: 'Senior Tech Tier',
    status: 'RUNNING',
    expiring: true,
    daysLeft: 18,
  },
  {
    id: 'CNT-2021-0118',
    contract_ref: 'CNT-2021-0118',
    employee: 'Devika Chawla',
    employee_name: 'Devika Chawla',
    empId: 'EMP-0419',
    employee_id: 'emp-3',
    role: 'Human Resources',
    avatar: 'https://i.pravatar.cc/150?u=d',
    start_date: '15 Jan 2021',
    end_date: 'Permanent / Indefinite',
    wage: '₹1,95,000',
    wage_amount: 195000,
    structure: 'Standard Fixed Band',
    status: 'RUNNING',
    expiring: false,
  },
  {
    id: 'CNT-2026-0042',
    contract_ref: 'CON/2026/0042',
    employee: 'Aarav Mehta',
    employee_name: 'Aarav Mehta',
    empId: 'EMP-0012',
    employee_id: 'emp-4',
    role: 'Finance Specialist',
    avatar: 'https://i.pravatar.cc/150?u=1',
    start_date: '01 Jan 2026',
    end_date: '31 Dec 2027',
    wage: '₹85,000',
    wage_amount: 85000,
    structure: 'Regular Salary Structure',
    status: 'RUNNING',
    expiring: false,
  },
];

export const mockAttendanceRecords = [
  { id: 'att-1', date: '02-Sep-2026', employee_name: 'Ananya Sharma', check_in: '2026-09-02T09:00:00Z', check_out: '2026-09-02T18:00:00Z', net_hours: 9.0, status: 'PRESENT', is_exception: false },
  { id: 'att-2', date: '02-Sep-2026', employee_name: 'Marcus Brody', check_in: '2026-09-02T09:35:00Z', check_out: '2026-09-02T18:05:00Z', net_hours: 8.5, status: 'LATE', is_exception: true },
  { id: 'att-3', date: '02-Sep-2026', employee_name: 'Elena Vance', check_in: '2026-09-02T08:50:00Z', check_out: '2026-09-02T18:30:00Z', net_hours: 9.6, status: 'PRESENT', is_exception: false },
  { id: 'att-4', date: '02-Sep-2026', employee_name: 'Vikram Sen', check_in: '2026-09-02T09:05:00Z', check_out: '2026-09-02T17:55:00Z', net_hours: 8.8, status: 'PRESENT', is_exception: false },
  { id: 'att-5', date: '02-Sep-2026', employee_name: 'Priya Patel', check_in: null, check_out: null, net_hours: 0, status: 'ON_LEAVE', is_exception: false },
];

export const mockTimeOffRequests = [
  { id: 'req-1', employee_name: 'Aarav Mehta', leave_type_name: 'Paid Time Off', start_date: '2026-09-12', end_date: '2026-09-14', duration_days: 3, status: 'PENDING', reason: 'Family vacation' },
  { id: 'req-2', employee_name: 'Marcus Brody', leave_type_name: 'Sick Leave', start_date: '2026-09-05', end_date: '2026-09-05', duration_days: 1, status: 'APPROVED', reason: 'Medical appointment' },
  { id: 'req-3', employee_name: 'Elena Vance', leave_type_name: 'Comp Off', start_date: '2026-08-28', end_date: '2026-08-29', duration_days: 2, status: 'APPROVED', reason: 'Weekend deploy compensatory' },
];

export const mockAllocations = [
  { id: 'alloc-1', employee_name: 'Aarav Mehta', leave_type_name: 'Paid Time Off', allocated_days: 24, taken_days: 6, remaining_days: 18, status: 'APPROVED' },
  { id: 'alloc-2', employee_name: 'Ananya Sharma', leave_type_name: 'Paid Time Off', allocated_days: 24, taken_days: 8, remaining_days: 16, status: 'APPROVED' },
  { id: 'alloc-3', employee_name: 'Marcus Brody', leave_type_name: 'Comp Off', allocated_days: 5, taken_days: 1, remaining_days: 4, status: 'APPROVED' },
];

export const mockLeaveTypes = [
  { id: 'lt-1', name: 'Paid Time Off', code: 'PTO', unit: 'Days', requires_allocation: true, display_color: '#005166' },
  { id: 'lt-2', name: 'Sick Leave', code: 'SL', unit: 'Days', requires_allocation: true, display_color: '#B71C1C' },
  { id: 'lt-3', name: 'Compensatory Off', code: 'COMP', unit: 'Days', requires_allocation: false, display_color: '#3B123F' },
];

export const mockPayruns = [
  { id: 'pr-1', name: 'September 2026 Regular Payrun', period_start: '2026-09-01', period_end: '2026-09-30', employee_count: 248, status: 'COMPUTED', warning_count: 2, total_gross: 2450000, total_deductions: 210000, total_net: 2240000 },
  { id: 'pr-2', name: 'August 2026 Regular Payrun', period_start: '2026-08-01', period_end: '2026-08-31', employee_count: 242, status: 'PAID', warning_count: 0, total_gross: 2380000, total_deductions: 205000, total_net: 2175000 },
];

export const mockPayslips = [
  { id: 'ps-1', employee_name: 'Ananya Sharma', worked_days: 22, basic: 140000, gross: 285000, net: 260000, status: 'Computed', has_warning: false },
  { id: 'ps-2', employee_name: 'Marcus Brody', worked_days: 21, basic: 105000, gross: 210000, net: 192000, status: 'Computed', has_warning: true, warning_reason: 'A/C verification pending' },
  { id: 'ps-3', employee_name: 'Elena Vance', worked_days: 22, basic: 160000, gross: 320000, net: 295000, status: 'Computed', has_warning: false },
  { id: 'ps-4', employee_name: 'Aarav Mehta', worked_days: 22, basic: 50000, gross: 85000, net: 78500, status: 'Computed', has_warning: false },
];

export const mockSalaryStructures = [
  { id: 'ss-1', name: 'Regular Salary Structure', code: 'REG_SAL', rule_count: 7, active: true },
  { id: 'ss-2', name: 'Executive Leadership Band', code: 'EXEC_BAND', rule_count: 9, active: true },
  { id: 'ss-3', name: 'Contract / Fixed Retainer', code: 'CONTRACTOR', rule_count: 3, active: true },
];

export const mockSalaryRules = [
  { id: 'sr-1', sequence: 10, name: 'Basic Salary', code: 'BASIC', category: 'BASIC', computation_method: 'PERCENTAGE', percentage: 50, percentage_base_code: 'WAGE' },
  { id: 'sr-2', sequence: 20, name: 'House Rent Allowance', code: 'HRA', category: 'ALLOWANCE', computation_method: 'PERCENTAGE', percentage: 40, percentage_base_code: 'BASIC' },
  { id: 'sr-3', sequence: 30, name: 'Special Allowance', code: 'SA', category: 'ALLOWANCE', computation_method: 'FORMULA', formula_expression: 'contract.wage - (BASIC + HRA)' },
  { id: 'sr-4', sequence: 100, name: 'Gross Pay', code: 'GROSS', category: 'GROSS', computation_method: 'FORMULA', formula_expression: 'categories.BASIC + categories.ALLOWANCE' },
  { id: 'sr-5', sequence: 200, name: 'Provident Fund (PF)', code: 'PF', category: 'DEDUCTION', computation_method: 'PERCENTAGE', percentage: 12, percentage_base_code: 'BASIC' },
  { id: 'sr-6', sequence: 210, name: 'Professional Tax (PT)', code: 'PT', category: 'DEDUCTION', computation_method: 'FIXED', amount: 200 },
  { id: 'sr-7', sequence: 300, name: 'Net Salary Disbursal', code: 'NET', category: 'NET', computation_method: 'FORMULA', formula_expression: 'GROSS - categories.DEDUCTION' },
];

export const mockDashboardSummary = {
  total_net_salary_paid: 2240000,
  payslips_generated: 248,
  avg_salary_per_employee: 85200,
  approved_time_off_days: 34,
  attendance_health: 96.5,
};
