// PeoplePay360 - Comprehensive Realistic Mock Dataset matching contracts/openapi.yaml

import {
  UserResponse,
  EmployeeDetailOut,
  DepartmentOut,
  ContractOut,
  ScheduleOut,
  AttendanceOut,
  LeaveTypeOut,
  AllocationOut,
  LeaveRequestOut,
  SalaryStructureOut,
  SalaryRuleOut,
  PayrunDetailOut,
  PayslipDetailOut,
  DashboardSummaryOut,
  AttendanceOverviewOut,
  TimeOffOverviewOut,
  DepartmentOverviewOut,
  DepartmentSalaryCostChart,
  MonthlyNetSalaryTrendChart,
  EligibleEmployeePreview,
} from '../types/api';

export const mockUsers: UserResponse[] = [
  {
    id: 'u-1',
    emp_id: 'emp-1',
    email: 'admin@peoplepay360.com',
    role: 'ADMIN',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'u-2',
    emp_id: 'emp-2',
    email: 'priya.sharma@peoplepay360.com',
    role: 'HR_MANAGER',
    is_active: true,
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'u-3',
    emp_id: 'emp-1',
    email: 'aarav.mehta@peoplepay360.com',
    role: 'HR_PAYROLL_MANAGER',
    is_active: true,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'u-4',
    emp_id: 'emp-3',
    email: 'rohan.verma@peoplepay360.com',
    role: 'EMPLOYEE',
    is_active: true,
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
  },
];

export const mockDepartments: DepartmentOut[] = [
  { id: 'dept-1', name: 'Engineering & Tech', code: 'ENG', manager_name: 'Rohan Verma' },
  { id: 'dept-2', name: 'People & Culture', code: 'HR', manager_name: 'Priya Sharma' },
  { id: 'dept-3', name: 'Finance & Payroll', code: 'FIN', manager_name: 'Aarav Mehta' },
  { id: 'dept-4', name: 'Product & Design', code: 'PRD', manager_name: 'Vikram Singh' },
  { id: 'dept-5', name: 'Growth & Marketing', code: 'MKT', manager_name: 'Neha Patel' },
];

export const mockSchedules: ScheduleOut[] = [
  {
    id: 'sched-1',
    name: 'Standard 40 Hours/Week',
    calendar_type: 'Full-Time',
    hours_per_week: 40.0,
    days_per_week: 5,
    lines: [
      { day_of_week: 0, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 1, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 2, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 3, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 4, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
    ],
  },
];

export const mockSalaryStructures: SalaryStructureOut[] = [
  {
    id: 'struct-1',
    name: 'Regular Full-Time Structure',
    code: 'REG_SAL',
    rule_count: 8,
    active: true,
    description: 'Standard enterprise salary structure with PF, HRA, and allowances',
  },
];

export const mockSalaryRules: Record<string, SalaryRuleOut[]> = {
  'struct-1': [
    { id: 'r-1', sequence: 10, name: 'Basic Salary', code: 'BASIC', category: 'BASIC', computation_method: 'PERCENTAGE', percentage: 50.0, percentage_base_code: 'WAGE' },
    { id: 'r-2', sequence: 20, name: 'House Rent Allowance', code: 'HRA', category: 'ALLOWANCE', computation_method: 'PERCENTAGE', percentage: 40.0, percentage_base_code: 'BASIC' },
    { id: 'r-3', sequence: 30, name: 'Conveyance Allowance', code: 'CONV', category: 'ALLOWANCE', computation_method: 'FIXED', amount: 3200 },
    { id: 'r-4', sequence: 40, name: 'Special Allowance', code: 'SPEC', category: 'ALLOWANCE', computation_method: 'FORMULA', formula_expression: 'WAGE - (BASIC + HRA + CONV)' },
    { id: 'r-5', sequence: 50, name: 'Gross Earnings', code: 'GROSS', category: 'GROSS', computation_method: 'FORMULA', formula_expression: 'BASIC + HRA + CONV + SPEC' },
    { id: 'r-6', sequence: 60, name: 'Provident Fund (Employee)', code: 'PF', category: 'DEDUCTION', computation_method: 'PERCENTAGE', percentage: 12.0, percentage_base_code: 'BASIC' },
    { id: 'r-7', sequence: 70, name: 'Professional Tax', code: 'PT', category: 'DEDUCTION', computation_method: 'FIXED', amount: 200 },
    { id: 'r-8', sequence: 80, name: 'Net Pay', code: 'NET', category: 'NET', computation_method: 'FORMULA', formula_expression: 'GROSS - (PF + PT)' },
  ],
};

export const mockEmployees: EmployeeDetailOut[] = [
  {
    id: 'emp-1',
    employee_code: 'EMP001',
    first_name: 'Aarav',
    last_name: 'Mehta',
    work_email: 'aarav.mehta@peoplepay360.com',
    phone: '+91 98765 43210',
    job_title: 'Lead Payroll Specialist',
    department_id: 'dept-3',
    department_name: 'Finance & Payroll',
    employee_type: 'FULL_TIME',
    join_date: '2024-03-15',
    is_active: true,
    bank_name: 'HDFC Bank',
    bank_account_number: '50100492817291',
    ifsc_code: 'HDFC0001234',
    smart_button_counts: { contracts: 1, attendance: 22, timeoff: 2 },
  },
  {
    id: 'emp-2',
    employee_code: 'EMP002',
    first_name: 'Priya',
    last_name: 'Sharma',
    work_email: 'priya.sharma@peoplepay360.com',
    phone: '+91 98123 45678',
    job_title: 'Head of Human Resources',
    department_id: 'dept-2',
    department_name: 'People & Culture',
    employee_type: 'FULL_TIME',
    join_date: '2023-08-01',
    is_active: true,
    bank_name: 'ICICI Bank',
    bank_account_number: '002101567890',
    ifsc_code: 'ICIC0000021',
    smart_button_counts: { contracts: 1, attendance: 21, timeoff: 1 },
  },
  {
    id: 'emp-3',
    employee_code: 'EMP003',
    first_name: 'Rohan',
    last_name: 'Verma',
    work_email: 'rohan.verma@peoplepay360.com',
    phone: '+91 97654 32109',
    job_title: 'Senior Full Stack Engineer',
    department_id: 'dept-1',
    department_name: 'Engineering & Tech',
    employee_type: 'FULL_TIME',
    join_date: '2023-11-10',
    is_active: true,
    bank_name: 'Axis Bank',
    bank_account_number: '912010034567812',
    ifsc_code: 'UTIB0000123',
    smart_button_counts: { contracts: 1, attendance: 20, timeoff: 3 },
  },
  {
    id: 'emp-4',
    employee_code: 'EMP004',
    first_name: 'Vikram',
    last_name: 'Singh',
    work_email: 'vikram.singh@peoplepay360.com',
    phone: '+91 95432 10987',
    job_title: 'Lead Product Designer',
    department_id: 'dept-4',
    department_name: 'Product & Design',
    employee_type: 'FULL_TIME',
    join_date: '2024-01-20',
    is_active: true,
    bank_name: 'State Bank of India',
    bank_account_number: '30981273412',
    ifsc_code: 'SBIN0004567',
    smart_button_counts: { contracts: 1, attendance: 19, timeoff: 0 },
  },
  {
    id: 'emp-5',
    employee_code: 'EMP005',
    first_name: 'Neha',
    last_name: 'Patel',
    work_email: 'neha.patel@peoplepay360.com',
    phone: '+91 94321 09876',
    job_title: 'Growth Marketing Lead',
    department_id: 'dept-5',
    department_name: 'Growth & Marketing',
    employee_type: 'FULL_TIME',
    join_date: '2024-04-01',
    is_active: true,
    bank_name: 'Kotak Mahindra Bank',
    bank_account_number: '8012349012',
    ifsc_code: 'KKBK0000456',
    smart_button_counts: { contracts: 1, attendance: 22, timeoff: 1 },
  },
  {
    id: 'emp-6',
    employee_code: 'EMP006',
    first_name: 'Ananya',
    last_name: 'Iyer',
    work_email: 'ananya.iyer@peoplepay360.com',
    phone: '+91 93210 98765',
    job_title: 'Senior Financial Analyst',
    department_id: 'dept-3',
    department_name: 'Finance & Payroll',
    employee_type: 'FULL_TIME',
    join_date: '2024-02-15',
    is_active: true,
    bank_name: 'HDFC Bank',
    bank_account_number: '50100876543210',
    ifsc_code: 'HDFC0001234',
    smart_button_counts: { contracts: 1, attendance: 23, timeoff: 0 },
  },
];

export const mockContracts: ContractOut[] = [
  {
    id: 'con-1',
    reference: 'CON-2024-001',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    schedule_id: 'sched-1',
    schedule_name: 'Standard 40 Hours/Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Full-Time Structure',
    start_date: '2024-03-15',
    end_date: null,
    wage: 85000,
    status: 'RUNNING',
  },
  {
    id: 'con-2',
    reference: 'CON-2023-002',
    employee_id: 'emp-2',
    employee_name: 'Priya Sharma',
    schedule_id: 'sched-1',
    schedule_name: 'Standard 40 Hours/Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Full-Time Structure',
    start_date: '2023-08-01',
    end_date: null,
    wage: 95000,
    status: 'RUNNING',
  },
  {
    id: 'con-3',
    reference: 'CON-2023-003',
    employee_id: 'emp-3',
    employee_name: 'Rohan Verma',
    schedule_id: 'sched-1',
    schedule_name: 'Standard 40 Hours/Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Full-Time Structure',
    start_date: '2023-11-10',
    end_date: null,
    wage: 110000,
    status: 'RUNNING',
  },
  {
    id: 'con-4',
    reference: 'CON-2024-004',
    employee_id: 'emp-4',
    employee_name: 'Vikram Singh',
    schedule_id: 'sched-1',
    schedule_name: 'Standard 40 Hours/Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Full-Time Structure',
    start_date: '2024-01-20',
    end_date: null,
    wage: 80000,
    status: 'RUNNING',
  },
  {
    id: 'con-5',
    reference: 'CON-2024-005',
    employee_id: 'emp-5',
    employee_name: 'Neha Patel',
    schedule_id: 'sched-1',
    schedule_name: 'Standard 40 Hours/Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Full-Time Structure',
    start_date: '2024-04-01',
    end_date: null,
    wage: 75000,
    status: 'RUNNING',
  },
  {
    id: 'con-6',
    reference: 'CON-2024-006',
    employee_id: 'emp-6',
    employee_name: 'Ananya Iyer',
    schedule_id: 'sched-1',
    schedule_name: 'Standard 40 Hours/Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Full-Time Structure',
    start_date: '2024-02-15',
    end_date: null,
    wage: 70000,
    status: 'RUNNING',
  },
];

export const mockAttendanceRecords: AttendanceOut[] = [
  {
    id: 'att-1',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    date: '2026-09-05',
    check_in: '2026-09-05T09:02:14Z',
    check_out: null,
    elapsed_hours: 4.8,
    net_hours: 4.8,
    status: 'PRESENT',
    is_exception: false,
  },
  {
    id: 'att-2',
    employee_id: 'emp-2',
    employee_name: 'Priya Sharma',
    date: '2026-09-05',
    check_in: '2026-09-05T08:55:00Z',
    check_out: null,
    elapsed_hours: 4.9,
    net_hours: 4.9,
    status: 'PRESENT',
    is_exception: false,
  },
  {
    id: 'att-3',
    employee_id: 'emp-3',
    employee_name: 'Rohan Verma',
    date: '2026-09-05',
    check_in: '2026-09-05T09:42:10Z',
    check_out: null,
    elapsed_hours: 4.1,
    net_hours: 4.1,
    status: 'LATE',
    is_exception: true,
  },
  {
    id: 'att-4',
    employee_id: 'emp-4',
    employee_name: 'Vikram Singh',
    date: '2026-09-04',
    check_in: '2026-09-04T09:00:00Z',
    check_out: '2026-09-04T19:30:00Z',
    elapsed_hours: 10.5,
    net_hours: 9.5,
    status: 'OVERTIME',
    is_exception: true,
  },
  {
    id: 'att-5',
    employee_id: 'emp-5',
    employee_name: 'Neha Patel',
    date: '2026-09-04',
    check_in: '2026-09-04T09:10:00Z',
    check_out: null,
    elapsed_hours: null,
    net_hours: null,
    status: 'MISSING_CHECKOUT',
    is_exception: true,
  },
];

export const mockLeaveTypes: LeaveTypeOut[] = [
  { id: 'lt-1', name: 'Paid Time Off', code: 'PTO', unit: 'DAYS', requires_allocation: true, display_color: '#005166' },
  { id: 'lt-2', name: 'Sick Leave', code: 'SICK', unit: 'DAYS', requires_allocation: true, display_color: '#BA1A1A' },
  { id: 'lt-3', name: 'Casual Leave', code: 'CASUAL', unit: 'DAYS', requires_allocation: true, display_color: '#3B123F' },
  { id: 'lt-4', name: 'Unpaid Leave', code: 'UNPAID', unit: 'DAYS', requires_allocation: false, display_color: '#7F747D' },
];

export const mockAllocations: AllocationOut[] = [
  {
    id: 'alloc-1',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    leave_type_name: 'Paid Time Off',
    allocated_days: 20.0,
    taken_days: 4.0,
    remaining_days: 16.0,
    validity_start: '2026-01-01',
    validity_end: '2026-12-31',
    status: 'APPROVED',
  },
  {
    id: 'alloc-2',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    leave_type_name: 'Sick Leave',
    allocated_days: 12.0,
    taken_days: 1.0,
    remaining_days: 11.0,
    validity_start: '2026-01-01',
    validity_end: '2026-12-31',
    status: 'APPROVED',
  },
  {
    id: 'alloc-3',
    employee_id: 'emp-3',
    employee_name: 'Rohan Verma',
    leave_type_name: 'Paid Time Off',
    allocated_days: 22.0,
    taken_days: 6.0,
    remaining_days: 16.0,
    validity_start: '2026-01-01',
    validity_end: '2026-12-31',
    status: 'APPROVED',
  },
];

export const mockLeaveRequests: LeaveRequestOut[] = [
  {
    id: 'lr-1',
    employee_id: 'emp-3',
    employee_name: 'Rohan Verma',
    leave_type_name: 'Paid Time Off',
    start_date: '2026-09-15',
    end_date: '2026-09-17',
    duration_days: 3,
    reason: 'Family event and short vacation',
    status: 'PENDING',
  },
  {
    id: 'lr-2',
    employee_id: 'emp-5',
    employee_name: 'Neha Patel',
    leave_type_name: 'Sick Leave',
    start_date: '2026-09-08',
    end_date: '2026-09-08',
    duration_days: 1,
    reason: 'Medical checkup',
    status: 'PENDING',
  },
  {
    id: 'lr-3',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    leave_type_name: 'Paid Time Off',
    start_date: '2026-08-10',
    end_date: '2026-08-12',
    duration_days: 3,
    reason: 'Personal time off',
    status: 'APPROVED',
  },
];

export const mockPayruns: PayrunDetailOut[] = [
  {
    id: 'payrun-aug-2026',
    name: 'August 2026 Regular Payroll',
    salary_structure_name: 'Regular Full-Time Structure',
    period_start: '2026-08-01',
    period_end: '2026-08-31',
    status: 'PAID',
    employee_count: 6,
    warning_count: 0,
    total_gross: 515000,
    total_deductions: 32100,
    total_net: 482900,
    payslips: [
      { id: 'ps-1', employee_name: 'Aarav Mehta', worked_days: 22, basic: 42500, gross: 85000, net: 79700, status: 'Paid', has_warning: false },
      { id: 'ps-2', employee_name: 'Priya Sharma', worked_days: 22, basic: 47500, gross: 95000, net: 89100, status: 'Paid', has_warning: false },
      { id: 'ps-3', employee_name: 'Rohan Verma', worked_days: 22, basic: 55000, gross: 110000, net: 103200, status: 'Paid', has_warning: false },
      { id: 'ps-4', employee_name: 'Vikram Singh', worked_days: 22, basic: 40000, gross: 80000, net: 75000, status: 'Paid', has_warning: false },
      { id: 'ps-5', employee_name: 'Neha Patel', worked_days: 22, basic: 37500, gross: 75000, net: 70300, status: 'Paid', has_warning: false },
      { id: 'ps-6', employee_name: 'Ananya Iyer', worked_days: 22, basic: 35000, gross: 70000, net: 65600, status: 'Paid', has_warning: false },
    ],
  },
  {
    id: 'payrun-sep-2026',
    name: 'September 2026 Regular Payroll',
    salary_structure_name: 'Regular Full-Time Structure',
    period_start: '2026-09-01',
    period_end: '2026-09-30',
    status: 'DRAFT',
    employee_count: 6,
    warning_count: 1,
    total_gross: 515000,
    total_deductions: 32100,
    total_net: 482900,
    payslips: [
      { id: 'ps-sep-1', employee_name: 'Aarav Mehta', worked_days: 22, basic: 42500, gross: 85000, net: 79700, status: 'Draft', has_warning: false },
      { id: 'ps-sep-2', employee_name: 'Priya Sharma', worked_days: 22, basic: 47500, gross: 95000, net: 89100, status: 'Draft', has_warning: false },
      { id: 'ps-sep-3', employee_name: 'Rohan Verma', worked_days: 22, basic: 55000, gross: 110000, net: 103200, status: 'Draft', has_warning: true, warning_reason: 'Pending leave request during period' },
      { id: 'ps-sep-4', employee_name: 'Vikram Singh', worked_days: 22, basic: 40000, gross: 80000, net: 75000, status: 'Draft', has_warning: false },
      { id: 'ps-sep-5', employee_name: 'Neha Patel', worked_days: 22, basic: 37500, gross: 75000, net: 70300, status: 'Draft', has_warning: false },
      { id: 'ps-sep-6', employee_name: 'Ananya Iyer', worked_days: 22, basic: 35000, gross: 70000, net: 65600, status: 'Draft', has_warning: false },
    ],
  },
];

export const mockPayslipDetails: Record<string, PayslipDetailOut> = {
  'ps-sep-1': {
    id: 'ps-sep-1',
    employee_name: 'Aarav Mehta',
    structure_name: 'Regular Full-Time Structure',
    payrun_name: 'September 2026 Regular Payroll',
    period_start: '2026-09-01',
    period_end: '2026-09-30',
    worked_days: 22,
    scheduled_days: 22,
    status: 'Draft',
    has_warning: false,
    lines: [
      { rule_sequence: 10, rule_name: 'Basic Salary', rule_code: 'BASIC', category: 'BASIC', quantity: 1, amount: 42500, total: 42500 },
      { rule_sequence: 20, rule_name: 'House Rent Allowance (40%)', rule_code: 'HRA', category: 'ALLOWANCE', rate: 40, quantity: 1, amount: 17000, total: 17000 },
      { rule_sequence: 30, rule_name: 'Conveyance Allowance', rule_code: 'CONV', category: 'ALLOWANCE', quantity: 1, amount: 3200, total: 3200 },
      { rule_sequence: 40, rule_name: 'Special Allowance', rule_code: 'SPEC', category: 'ALLOWANCE', quantity: 1, amount: 22300, total: 22300 },
      { rule_sequence: 50, rule_name: 'Gross Earnings', rule_code: 'GROSS', category: 'GROSS', quantity: 1, amount: 85000, total: 85000 },
      { rule_sequence: 60, rule_name: 'Provident Fund (12%)', rule_code: 'PF', category: 'DEDUCTION', rate: 12, quantity: 1, amount: 5100, total: 5100 },
      { rule_sequence: 70, rule_name: 'Professional Tax', rule_code: 'PT', category: 'DEDUCTION', quantity: 1, amount: 200, total: 200 },
      { rule_sequence: 80, rule_name: 'Net Pay', rule_code: 'NET', category: 'NET', quantity: 1, amount: 79700, total: 79700 },
    ],
  },
};

export const mockEligibleEmployees: EligibleEmployeePreview[] = [
  { employee_id: 'emp-1', employee_name: 'Aarav Mehta', department_name: 'Finance & Payroll', working_hours_per_week: 40, contract_start_date: '2024-03-15', wage: 85000 },
  { employee_id: 'emp-2', employee_name: 'Priya Sharma', department_name: 'People & Culture', working_hours_per_week: 40, contract_start_date: '2023-08-01', wage: 95000 },
  { employee_id: 'emp-3', employee_name: 'Rohan Verma', department_name: 'Engineering & Tech', working_hours_per_week: 40, contract_start_date: '2023-11-10', wage: 110000 },
  { employee_id: 'emp-4', employee_name: 'Vikram Singh', department_name: 'Product & Design', working_hours_per_week: 40, contract_start_date: '2024-01-20', wage: 80000 },
  { employee_id: 'emp-5', employee_name: 'Neha Patel', department_name: 'Growth & Marketing', working_hours_per_week: 40, contract_start_date: '2024-04-01', wage: 75000 },
  { employee_id: 'emp-6', employee_name: 'Ananya Iyer', department_name: 'Finance & Payroll', working_hours_per_week: 40, contract_start_date: '2024-02-15', wage: 70000 },
];

export const mockDashboardSummary: DashboardSummaryOut = {
  total_net_salary_paid: 482900,
  payslips_generated: 12,
  avg_salary_per_employee: 85833,
  approved_time_off_days: 7.0,
  attendance_health: 96.8,
};

export const mockAttendanceOverview: AttendanceOverviewOut = {
  present: 18,
  late: 2,
  absent: 1,
  overtime: 3,
  missing_checkouts: 1,
};

export const mockTimeOffOverview: TimeOffOverviewOut[] = [
  { leave_type: 'Paid Time Off', approved_days: 4.5, pending_requests: 2, remaining_balance: 16 },
  { leave_type: 'Sick Leave', approved_days: 1.0, pending_requests: 1, remaining_balance: 11 },
  { leave_type: 'Casual Leave', approved_days: 1.5, pending_requests: 0, remaining_balance: 8 },
];

export const mockDepartmentOverview: DepartmentOverviewOut[] = [
  { department: 'Engineering & Tech', headcount: 4, total_salary: 190000 },
  { department: 'Finance & Payroll', headcount: 3, total_salary: 155000 },
  { department: 'People & Culture', headcount: 2, total_salary: 95000 },
  { department: 'Product & Design', headcount: 2, total_salary: 80000 },
  { department: 'Growth & Marketing', headcount: 1, total_salary: 75000 },
];

export const mockSalaryCostByDept: DepartmentSalaryCostChart[] = [
  { department: 'Engineering', total_salary: 190000 },
  { department: 'Finance', total_salary: 155000 },
  { department: 'People/HR', total_salary: 95000 },
  { department: 'Product', total_salary: 80000 },
  { department: 'Marketing', total_salary: 75000 },
];

export const mockMonthlySalaryTrend: MonthlyNetSalaryTrendChart[] = [
  { month: '2026-04', net_amount: 440000 },
  { month: '2026-05', net_amount: 455000 },
  { month: '2026-06', net_amount: 460000 },
  { month: '2026-07', net_amount: 472000 },
  { month: '2026-08', net_amount: 482900 },
  { month: '2026-09', net_amount: 482900 },
];
