// PeoplePay360 - Comprehensive Realistic Mock Dataset matching contracts/openapi.yaml & HRMS OXP - 24 hours.excalidraw 1:1

import {
  UserResponse,
  EmployeeDetailOut,
  DepartmentOut,
  ContractOut,
  ScheduleOut,
  AttendanceOut,
  LeaveTypeOut,
  AllocationOut,
  LeaveRequestOut,
  SalaryStructureOut,
  SalaryRuleOut,
  PayrunDetailOut,
  PayslipDetailOut,
  DashboardSummaryOut,
  AttendanceOverviewOut,
  TimeOffOverviewOut,
  DepartmentOverviewOut,
  DepartmentSalaryCostChart,
  MonthlyNetSalaryTrendChart,
  EligibleEmployeePreview,
} from '../types/api';

export const mockUsers: UserResponse[] = [
  {
    id: 'u-1',
    emp_id: null,
    email: 'admin@company.com',
    role: 'ADMIN',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'u-2',
    emp_id: 'emp-2',
    email: 'maya@company.com',
    role: 'HR_MANAGER',
    is_active: true,
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'u-3',
    emp_id: 'emp-3',
    email: 'rohan@company.com',
    role: 'EMPLOYEE',
    is_active: true,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'u-4',
    emp_id: 'emp-4',
    email: 'nisha@company.com',
    role: 'HR_PAYROLL_MANAGER',
    is_active: true,
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-01-12T00:00:00Z',
  },
  {
    id: 'u-5',
    emp_id: 'emp-1',
    email: 'aarav@company.com',
    role: 'HR_PAYROLL_USER',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const mockDepartments: DepartmentOut[] = [
  { id: 'dept-1', name: 'Finance', code: 'FIN', manager_name: 'Aarav Mehta' },
  { id: 'dept-2', name: 'HR', code: 'HR', manager_name: 'Sara Khan' },
  { id: 'dept-3', name: 'IT', code: 'IT', manager_name: 'John Dsouza' },
  { id: 'dept-4', name: 'Sales', code: 'SALES', manager_name: 'Vikram Singh' },
  { id: 'dept-5', name: 'Support', code: 'SUP', manager_name: 'Neha Patel' },
];

export const mockSchedules: ScheduleOut[] = [
  {
    id: 'sched-1',
    name: '40 Hours / Week',
    calendar_type: 'Full-Time',
    hours_per_week: 40.0,
    days_per_week: 5,
    lines: [
      { day_of_week: 0, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 1, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 2, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 3, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 4, start_time: '09:00:00', end_time: '18:00:00', break_hours: 1.0, work_hours: 8.0 },
    ],
  },
  {
    id: 'sched-2',
    name: 'Night Shift',
    calendar_type: 'Full-Time Shift',
    hours_per_week: 40.0,
    days_per_week: 5,
    lines: [
      { day_of_week: 0, start_time: '21:00:00', end_time: '06:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 1, start_time: '21:00:00', end_time: '06:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 2, start_time: '21:00:00', end_time: '06:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 3, start_time: '21:00:00', end_time: '06:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 4, start_time: '21:00:00', end_time: '06:00:00', break_hours: 1.0, work_hours: 8.0 },
    ],
  },
  {
    id: 'sched-3',
    name: 'Retail Weekend',
    calendar_type: 'Shift',
    hours_per_week: 40.0,
    days_per_week: 5,
    lines: [
      { day_of_week: 2, start_time: '10:00:00', end_time: '19:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 3, start_time: '10:00:00', end_time: '19:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 4, start_time: '10:00:00', end_time: '19:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 5, start_time: '10:00:00', end_time: '19:00:00', break_hours: 1.0, work_hours: 8.0 },
      { day_of_week: 6, start_time: '10:00:00', end_time: '19:00:00', break_hours: 1.0, work_hours: 8.0 },
    ],
  },
  {
    id: 'sched-4',
    name: 'Flexible Hybrid',
    calendar_type: 'Hybrid',
    hours_per_week: 37.5,
    days_per_week: 5,
    lines: [
      { day_of_week: 0, start_time: '09:30:00', end_time: '17:30:00', break_hours: 0.5, work_hours: 7.5 },
      { day_of_week: 1, start_time: '09:30:00', end_time: '17:30:00', break_hours: 0.5, work_hours: 7.5 },
      { day_of_week: 2, start_time: '09:30:00', end_time: '17:30:00', break_hours: 0.5, work_hours: 7.5 },
      { day_of_week: 3, start_time: '09:30:00', end_time: '17:30:00', break_hours: 0.5, work_hours: 7.5 },
      { day_of_week: 4, start_time: '09:30:00', end_time: '17:30:00', break_hours: 0.5, work_hours: 7.5 },
    ],
  },
  {
    id: 'sched-5',
    name: 'Part-time 20h',
    calendar_type: 'Part-Time',
    hours_per_week: 20.0,
    days_per_week: 4,
    lines: [
      { day_of_week: 0, start_time: '09:00:00', end_time: '14:00:00', break_hours: 0.0, work_hours: 5.0 },
      { day_of_week: 1, start_time: '09:00:00', end_time: '14:00:00', break_hours: 0.0, work_hours: 5.0 },
      { day_of_week: 2, start_time: '09:00:00', end_time: '14:00:00', break_hours: 0.0, work_hours: 5.0 },
      { day_of_week: 3, start_time: '09:00:00', end_time: '14:00:00', break_hours: 0.0, work_hours: 5.0 },
    ],
  },
];

export const mockSalaryStructures: SalaryStructureOut[] = [
  {
    id: 'struct-1',
    name: 'Regular Salary',
    code: 'REG_SAL',
    rule_count: 12,
    active: true,
    description: 'Enterprise standard salary structure with HRA, standard allowances, PF, and PT',
  },
  {
    id: 'struct-2',
    name: 'Intern Salary',
    code: 'INTERN_SAL',
    rule_count: 8,
    active: true,
    description: 'Fixed monthly stipend structure with zero statutory deductions',
  },
  {
    id: 'struct-3',
    name: 'Contractor',
    code: 'CONTRACT_SAL',
    rule_count: 6,
    active: true,
    description: 'Daily / hourly invoice compensation with withholding tax',
  },
];

export const mockSalaryRules: Record<string, SalaryRuleOut[]> = {
  'struct-1': [
    { id: 'r-1', sequence: 1, name: 'Basic Salary', code: 'BASIC', category: 'BASIC', computation_method: 'PERCENTAGE', percentage: 50.0, percentage_base_code: 'WAGE' },
    { id: 'r-2', sequence: 10, name: 'House Rent Allowance', code: 'HRA', category: 'ALLOWANCE', computation_method: 'PERCENTAGE', percentage: 40.0, percentage_base_code: 'BASIC' },
    { id: 'r-3', sequence: 20, name: 'Standard Allowance', code: 'STD', category: 'ALLOWANCE', computation_method: 'FIXED', amount: 10000 },
    { id: 'r-4', sequence: 30, name: 'Performance Bonus', code: 'BONUS', category: 'ALLOWANCE', computation_method: 'FIXED', amount: 5000 },
    { id: 'r-5', sequence: 40, name: 'Leave Travel Allowance', code: 'LTA', category: 'ALLOWANCE', computation_method: 'FIXED', amount: 3000 },
    { id: 'r-6', sequence: 50, name: 'Fixed Allowance', code: 'FIX', category: 'ALLOWANCE', computation_method: 'FIXED', amount: 2000 },
    { id: 'r-7', sequence: 60, name: 'Gross Salary', code: 'GROSS', category: 'GROSS', computation_method: 'FORMULA', formula_expression: 'BASIC + HRA + STD + BONUS + LTA + FIX' },
    { id: 'r-8', sequence: 70, name: 'LWF fund', code: 'LWF', category: 'DEDUCTION', computation_method: 'FIXED', amount: 50 },
    { id: 'r-9', sequence: 80, name: 'Provident Fund', code: 'PF', category: 'DEDUCTION', computation_method: 'PERCENTAGE', percentage: 12.0, percentage_base_code: 'BASIC' },
    { id: 'r-10', sequence: 90, name: 'ESIC', code: 'ESIC', category: 'DEDUCTION', computation_method: 'PERCENTAGE', percentage: 0.75, percentage_base_code: 'GROSS' },
    { id: 'r-11', sequence: 100, name: 'Professional Tax', code: 'PT', category: 'DEDUCTION', computation_method: 'FIXED', amount: 200 },
    { id: 'r-12', sequence: 110, name: 'Net Salary', code: 'NET', category: 'NET', computation_method: 'FORMULA', formula_expression: 'GROSS - (LWF + PF + ESIC + PT)' },
  ],
};

export const mockEmployees: EmployeeDetailOut[] = [
  {
    id: 'emp-1',
    employee_code: 'EMP001',
    first_name: 'Aarav',
    last_name: 'Mehta',
    work_email: 'aarav@oxp.com',
    phone: '+91 98765 43210',
    job_title: 'Payroll Specialist',
    department_id: 'dept-1',
    department_name: 'Finance',
    employee_type: 'FULL_TIME',
    join_date: '2024-03-15',
    is_active: true,
    bank_name: 'HDFC Bank',
    bank_account_number: '50100492817291',
    ifsc_code: 'HDFC0001234',
    smart_button_counts: { contracts: 2, attendance: 14, timeoff: 3 },
  },
  {
    id: 'emp-2',
    employee_code: 'EMP002',
    first_name: 'Sara',
    last_name: 'Khan',
    work_email: 'sara@oxp.com',
    phone: '+91 98123 45678',
    job_title: 'HR Officer',
    department_id: 'dept-2',
    department_name: 'HR',
    employee_type: 'FULL_TIME',
    join_date: '2023-08-01',
    is_active: true,
    bank_name: null,
    bank_account_number: null,
    ifsc_code: null,
    smart_button_counts: { contracts: 1, attendance: 22, timeoff: 1 },
  },
  {
    id: 'emp-3',
    employee_code: 'EMP003',
    first_name: 'John',
    last_name: 'Dsouza',
    work_email: 'john@oxp.com',
    phone: '+91 97654 32109',
    job_title: 'Developer',
    department_id: 'dept-3',
    department_name: 'IT',
    employee_type: 'FULL_TIME',
    join_date: '2023-11-10',
    is_active: true,
    bank_name: 'Axis Bank',
    bank_account_number: '912010034567812',
    ifsc_code: 'UTIB0000123',
    smart_button_counts: { contracts: 1, attendance: 20, timeoff: 1 },
  },
  {
    id: 'emp-4',
    employee_code: 'EMP004',
    first_name: 'Neha',
    last_name: 'Patel',
    work_email: 'neha@oxp.com',
    phone: '+91 94321 09876',
    job_title: 'Recruiter',
    department_id: 'dept-2',
    department_name: 'HR',
    employee_type: 'FULL_TIME',
    join_date: '2024-04-01',
    is_active: true,
    bank_name: 'Kotak Mahindra Bank',
    bank_account_number: '8012349012',
    ifsc_code: 'KKBK0000456',
    smart_button_counts: { contracts: 1, attendance: 18, timeoff: 2 },
  },
  {
    id: 'emp-5',
    employee_code: 'EMP005',
    first_name: 'Vikram',
    last_name: 'Singh',
    work_email: 'vikram@oxp.com',
    phone: '+91 95432 10987',
    job_title: 'Sales Lead',
    department_id: 'dept-4',
    department_name: 'Sales',
    employee_type: 'FULL_TIME',
    join_date: '2024-01-20',
    is_active: true,
    bank_name: 'State Bank of India',
    bank_account_number: '30981273412',
    ifsc_code: 'SBIN0004567',
    smart_button_counts: { contracts: 1, attendance: 19, timeoff: 0 },
  },
];

export const mockContracts: ContractOut[] = [
  {
    id: 'con-1',
    reference: 'CON/2026/0042',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    schedule_id: 'sched-1',
    schedule_name: '40 Hours / Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Salary',
    start_date: '2026-01-01',
    end_date: null,
    wage: 85000,
    status: 'RUNNING',
  },
  {
    id: 'con-2',
    reference: 'CON/2025/0018',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    schedule_id: 'sched-1',
    schedule_name: '40 Hours / Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Salary',
    start_date: '2025-07-01',
    end_date: '2025-12-31',
    wage: 78000,
    status: 'EXPIRED',
  },
  {
    id: 'con-3',
    reference: 'CON/2026/0031',
    employee_id: 'emp-2',
    employee_name: 'Sara Khan',
    schedule_id: 'sched-1',
    schedule_name: '40 Hours / Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Salary',
    start_date: '2026-01-01',
    end_date: null,
    wage: 95000,
    status: 'RUNNING',
  },
  {
    id: 'con-4',
    reference: 'CON/2026/0014',
    employee_id: 'emp-3',
    employee_name: 'John Dsouza',
    schedule_id: 'sched-1',
    schedule_name: '40 Hours / Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Salary',
    start_date: '2026-02-01',
    end_date: null,
    wage: 72000,
    status: 'RUNNING',
  },
  {
    id: 'con-5',
    reference: 'CON/2026/0022',
    employee_id: 'emp-4',
    employee_name: 'Neha Patel',
    schedule_id: 'sched-1',
    schedule_name: '40 Hours / Week',
    salary_structure_id: 'struct-1',
    salary_structure_name: 'Regular Salary',
    start_date: '2026-01-01',
    end_date: null,
    wage: 64000,
    status: 'RUNNING',
  },
];

export const mockAttendanceRecords: AttendanceOut[] = [
  {
    id: 'att-1',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    date: '2026-09-02',
    check_in: '2026-09-02T09:05:00Z',
    check_out: '2026-09-02T18:10:00Z',
    elapsed_hours: 9.08,
    net_hours: 8.58,
    status: 'PRESENT',
    is_exception: false,
  },
  {
    id: 'att-2',
    employee_id: 'emp-2',
    employee_name: 'Sara Khan',
    date: '2026-09-02',
    check_in: '2026-09-02T09:15:00Z',
    check_out: '2026-09-02T18:02:00Z',
    elapsed_hours: 8.78,
    net_hours: 8.0,
    status: 'PRESENT',
    is_exception: false,
  },
  {
    id: 'att-3',
    employee_id: 'emp-3',
    employee_name: 'John Dsouza',
    date: '2026-09-02',
    check_in: '2026-09-02T09:32:00Z',
    check_out: '2026-09-02T17:58:00Z',
    elapsed_hours: 8.43,
    net_hours: 7.9,
    status: 'PRESENT',
    is_exception: false,
  },
  {
    id: 'att-4',
    employee_id: 'emp-4',
    employee_name: 'Neha Patel',
    date: '2026-09-02',
    check_in: '',
    check_out: null,
    elapsed_hours: 0,
    net_hours: 0,
    status: 'MISSING_CHECKOUT',
    is_exception: true,
  },
];

export const mockLeaveTypes: LeaveTypeOut[] = [
  { id: 'lt-1', name: 'Paid Time Off', code: 'PTO', unit: 'DAYS', requires_allocation: true, display_color: '#005166' },
  { id: 'lt-2', name: 'Sick Leave', code: 'SICK', unit: 'DAYS', requires_allocation: false, display_color: '#BA1A1A' },
  { id: 'lt-3', name: 'Comp Off', code: 'COMPOFF', unit: 'HOURS', requires_allocation: true, display_color: '#3B123F' },
];

export const mockAllocations: AllocationOut[] = [
  {
    id: 'alloc-1',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    leave_type_name: 'Paid Time Off',
    allocated_days: 20.0,
    taken_days: 8.0,
    remaining_days: 12.0,
    validity_start: '2026-01-01',
    validity_end: '2026-12-31',
    status: 'APPROVED',
  },
  {
    id: 'alloc-2',
    employee_id: 'emp-2',
    employee_name: 'Sara Khan',
    leave_type_name: 'Paid Time Off',
    allocated_days: 18.0,
    taken_days: 4.0,
    remaining_days: 14.0,
    validity_start: '2026-01-01',
    validity_end: '2026-12-31',
    status: 'APPROVED',
  },
  {
    id: 'alloc-3',
    employee_id: 'emp-4',
    employee_name: 'Neha Patel',
    leave_type_name: 'Comp Off',
    allocated_days: 2.0,
    taken_days: 1.0,
    remaining_days: 1.0,
    validity_start: '2026-01-01',
    validity_end: '2026-12-31',
    status: 'DRAFT',
  },
];

export const mockLeaveRequests: LeaveRequestOut[] = [
  {
    id: 'lr-1',
    employee_id: 'emp-1',
    employee_name: 'Aarav Mehta',
    leave_type_name: 'Paid Time Off',
    start_date: '2026-09-12',
    end_date: '2026-09-14',
    duration_days: 3,
    reason: 'Family vacation',
    status: 'APPROVED',
  },
  {
    id: 'lr-2',
    employee_id: 'emp-2',
    employee_name: 'Sara Khan',
    leave_type_name: 'Sick Leave',
    start_date: '2026-09-18',
    end_date: '2026-09-18',
    duration_days: 1,
    reason: 'Medical rest',
    status: 'APPROVED',
  },
  {
    id: 'lr-3',
    employee_id: 'emp-3',
    employee_name: 'John Dsouza',
    leave_type_name: 'Comp Off',
    start_date: '2026-09-27',
    end_date: '2026-09-27',
    duration_days: 1,
    reason: 'Weekend deployment compensation',
    status: 'PENDING',
  },
];

export const mockPayruns: PayrunDetailOut[] = [
  {
    id: 'payrun-jan-2026',
    name: 'January 2026',
    salary_structure_name: 'Regular Salary',
    period_start: '2026-01-01',
    period_end: '2026-01-31',
    status: 'PAID',
    employee_count: 42,
    warning_count: 1,
    total_gross: 3360000,
    total_deductions: 210000,
    total_net: 3150000,
    payslips: [
      { id: 'ps-1', employee_name: 'Aarav Mehta', worked_days: 22, basic: 50000, gross: 80000, net: 75000, status: 'Paid', has_warning: false },
      { id: 'ps-2', employee_name: 'Sara Khan', worked_days: 22, basic: 60000, gross: 96000, net: 88000, status: 'Paid', has_warning: true, warning_reason: 'A/C missing' },
    ],
  },
  {
    id: 'payrun-feb-2026',
    name: 'February 2026',
    salary_structure_name: 'Regular Salary',
    period_start: '2026-02-01',
    period_end: '2026-02-28',
    status: 'VALIDATED',
    employee_count: 42,
    warning_count: 2,
    total_gross: 3360000,
    total_deductions: 210000,
    total_net: 3150000,
    payslips: [
      { id: 'ps-feb-1', employee_name: 'Aarav Mehta', worked_days: 22, basic: 50000, gross: 80000, net: 75000, status: 'Done', has_warning: false },
      { id: 'ps-feb-2', employee_name: 'Sara Khan', worked_days: 22, basic: 60000, gross: 96000, net: 88000, status: 'Done', has_warning: true, warning_reason: 'A/C missing' },
      { id: 'ps-feb-3', employee_name: 'John Dsouza', worked_days: 20, basic: 45000, gross: 72000, net: 66000, status: 'Draft', has_warning: true, warning_reason: 'Duplicate payslip warning' },
      { id: 'ps-feb-4', employee_name: 'Neha Patel', worked_days: 22, basic: 40000, gross: 64000, net: 59000, status: 'Done', has_warning: false },
    ],
  },
  {
    id: 'payrun-mar-2026',
    name: 'March 2026',
    salary_structure_name: 'Regular Salary',
    period_start: '2026-03-01',
    period_end: '2026-03-31',
    status: 'DRAFT',
    employee_count: 42,
    warning_count: 0,
    total_gross: 3360000,
    total_deductions: 210000,
    total_net: 3150000,
    payslips: [
      { id: 'ps-mar-1', employee_name: 'Aarav Mehta', worked_days: 22, basic: 50000, gross: 80000, net: 75000, status: 'Draft', has_warning: false },
      { id: 'ps-mar-2', employee_name: 'Sara Khan', worked_days: 22, basic: 60000, gross: 96000, net: 88000, status: 'Draft', has_warning: false },
    ],
  },
];

export const mockPayslipDetails: Record<string, PayslipDetailOut> = {
  'ps-feb-1': {
    id: 'ps-feb-1',
    employee_name: 'Aarav Mehta',
    structure_name: 'Regular Salary',
    payrun_name: 'February 2026',
    period_start: '2026-02-01',
    period_end: '2026-02-28',
    worked_days: 22,
    scheduled_days: 22,
    status: 'Done',
    has_warning: false,
    lines: [
      { rule_sequence: 1, rule_name: 'Basic Salary', rule_code: 'BASIC', category: 'Basic', quantity: 1, amount: 50000, total: 50000 },
      { rule_sequence: 10, rule_name: 'House Rent Allowance', rule_code: 'HRA', category: 'Allowance', quantity: 1, amount: 20000, total: 20000 },
      { rule_sequence: 20, rule_name: 'Standard Allowance', rule_code: 'STD', category: 'Allowance', quantity: 1, amount: 10000, total: 10000 },
      { rule_sequence: 60, rule_name: 'Gross Salary', rule_code: 'GROSS', category: 'Gross', quantity: 1, amount: 80000, total: 80000 },
      { rule_sequence: 80, rule_name: 'Provident Fund', rule_code: 'PF', category: 'Deduction', quantity: 1, amount: -3000, total: -3000 },
      { rule_sequence: 100, rule_name: 'Professional Tax', rule_code: 'PT', category: 'Deduction', quantity: 1, amount: -2000, total: -2000 },
      { rule_sequence: 110, rule_name: 'Net Salary', rule_code: 'NET', category: 'Net', quantity: 1, amount: 75000, total: 75000 },
    ],
  },
};

export const mockEligibleEmployees: EligibleEmployeePreview[] = [
  { employee_id: 'emp-1', employee_name: 'Aarav Mehta', department_name: 'Finance', working_hours_per_week: 40, contract_start_date: '2026-01-01', wage: 85000 },
  { employee_id: 'emp-2', employee_name: 'Sara Khan', department_name: 'HR', working_hours_per_week: 40, contract_start_date: '2026-01-01', wage: 95000 },
  { employee_id: 'emp-3', employee_name: 'John Dsouza', department_name: 'IT', working_hours_per_week: 40, contract_start_date: '2026-02-01', wage: 72000 },
  { employee_id: 'emp-4', employee_name: 'Neha Patel', department_name: 'HR', working_hours_per_week: 40, contract_start_date: '2026-01-01', wage: 64000 },
  { employee_id: 'emp-5', employee_name: 'Vikram Singh', department_name: 'Sales', working_hours_per_week: 40, contract_start_date: '2026-01-01', wage: 80000 },
];

export const mockDashboardSummary: DashboardSummaryOut = {
  total_net_salary_paid: 1840000,
  payslips_generated: 148,
  avg_salary_per_employee: 12432,
  approved_time_off_days: 34.0,
  attendance_health: 94.0,
};

export const mockAttendanceOverview: AttendanceOverviewOut = {
  present: 94,
  late: 18,
  absent: 9,
  overtime: 22,
  missing_checkouts: 5,
};

export const mockTimeOffOverview: TimeOffOverviewOut[] = [
  { leave_type: 'Paid Time Off', approved_days: 24, pending_requests: 3, remaining_balance: 118 },
  { leave_type: 'Sick Leave', approved_days: 6, pending_requests: 1, remaining_balance: null },
  { leave_type: 'Comp Off', approved_days: 4, pending_requests: 2, remaining_balance: 11 },
];

export const mockDepartmentOverview: DepartmentOverviewOut[] = [
  { department: 'IT', headcount: 18, total_salary: 420000 },
  { department: 'Sales', headcount: 22, total_salary: 570000 },
  { department: 'HR', headcount: 8, total_salary: 190000 },
  { department: 'Support', headcount: 14, total_salary: 310000 },
];

export const mockSalaryCostByDept: DepartmentSalaryCostChart[] = [
  { department: 'IT', total_salary: 170000 },
  { department: 'Sales', total_salary: 150000 },
  { department: 'Finance', total_salary: 130000 },
  { department: 'HR', total_salary: 110000 },
  { department: 'Support', total_salary: 90000 },
];

export const mockMonthlySalaryTrend: MonthlyNetSalaryTrendChart[] = [
  { month: 'Apr', net_amount: 1500000 },
  { month: 'May', net_amount: 1520000 },
  { month: 'Jun', net_amount: 1430000 },
  { month: 'Jul', net_amount: 1480000 },
  { month: 'Aug', net_amount: 1710000 },
  { month: 'Sep', net_amount: 1840000 },
];
